### ISSUE TITLE
Unknown error, script doesnt start (version 1.84)

### ISSUE THREAD

**Issue by coatsy22** [ensingm2/SteamMonsterGameScript#108]
I both upgraded to chrome x64 after a memory leak, and updated the script, so i'm not sure which is the culprit.

I get the following error message, and then the script doesnt do anything, though it still throws lag related messages (so some part of it is on).

Syntax error @ 'Steam Monster Game Script'!
###### 

JSHINT output:
require: (W033) Missing semicolon on line: 82 at character: 80
require: (W033) Missing semicolon on line: 83 at character: 80
script: (W033) Missing semicolon on line: 1416 at character: 6
script: (W033) Missing semicolon on line: 1419 at character: 177
script: (W033) Missing semicolon on line: 1420 at character: 6
script: (W033) Missing semicolon on line: 1442 at character: 6
script: (W033) Missing semicolon on line: 1476 at character: 79
script: (W033) Missing semicolon on line: 1477 at character: 83
script: (W033) Missing semicolon on line: 1478 at character: 91
script: (W033) Missing semicolon on line: 1479 at character: 103
script: (W033) Missing semicolon on line: 1480 at character: 98
script: (W033) Missing semicolon on line: 1481 at character: 92
script: (W033) Missing semicolon on line: 1482 at character: 98
script: (W033) Missing semicolon on line: 1483 at character: 85
script: (E030) Expected an identifier and instead saw ')' on line: 1622 at character: 22
script: (W030) Expected an assignment or function call and instead saw an expression on line: 1622 at character: 22
script: (W033) Missing semicolon on line: 1622 at character: 23
script: (W041) Use '===' to compare with 'null' on line: 1687 at character: 40
###### 

SyntaxError: Unexpected token )
    at Function (native)
    at e (<anonymous>:40:49)
    at Z (<anonymous>:40:103)
    at aa (<anonymous>:77:392)
    at b (<anonymous>:78:109)

**Comment by ensingm2** [comment]
You might've grabbed the code in the minute or so before the fix. Should be fixed as of https://github.com/ensingm2/SteamMonsterGameScript/commit/37a83f6ae94703e9fc9ac8fcf0901050139512ec, can you confirm?

**Comment by coatsy22** [comment]
I actually rebooted the computer, and the same script is working fine.

Looks like it was just an issue with installing chrome x64 and then not restarting.

Apologies for the trouble

**Comment by ensingm2** [comment]
Nah, there **_was**_ an error in the code for a little bit. After the restart your TamperMonkey probably auto-updated to the newly fixed script.
