### ISSUE TITLE
Disable ability use particles?

### ISSUE THREAD

**Issue by cdmichaelb** [ensingm2/SteamMonsterGameScript#114]
They aren't creating memory leaks as far as I can tell, but they are having a significant impact on performance (especially with multiple slaves open). Can those particles also be disabled?

**Comment by ensingm2** [comment]
> They aren't creating memory leaks as far as I can tell, but they are having a significant impact on performance

I'll look into an option to disable ability particles

> (especially with multiple slaves open)

I don't _think_ this should be the case. See [This renderer disabling code](https://github.com/ensingm2/SteamMonsterGameScript/blob/master/slaveWindows.js#L94-111), As the renderer is deleted, I don't think any particles should spawn in slaves. Are you sure it's not just the extra computation from the extra clicking/scripts?

**Comment by cdmichaelb** [comment]
It could be the script, I meant manual slaves though (since as discussed in other post I'm fairly certain the generated slaves don't work, and i'm 50/50 on manual slaves working), probably moot since slaves probably don't work at all.

But the particles are still an issue, even for a single client especially on early levels, so it'll be nice to have on new days.

**Comment by vanZeben** [comment]
Quickfix for effect particles, we can simply "CSceneGame.prototype.SpawnEmitter = function(){}", mind you that will start throwing errors since things aren't being caught correctly and an ability has to be inactive in the lane after you type this (as in it has to go inactive) before it will stop showing it, but if you dont care about console errors, throw that in your console

**Comment by vanZeben** [comment]
SteamDB's implementation just straight up disables the whole renderer and simulates 1fps themselves... We could merge that in?

**Comment by vanZeben** [comment]
See #148
