### ISSUE TITLE
Gaining new Crit items faster than they are used

### ISSUE THREAD

**Issue by thelulzy** [ensingm2/SteamMonsterGameScript#115]
I'm ending up with a surplus of unused Crit items due to a combination of the  the deployment conditions of Crit (which is what we need to fix), speed at which we're destroying levels, and my Boss Loot level.

Crit is rarely ever being auto deployed, and I believe an automatic deployment of it would only serve to increase DPS rates.

**Comment by GoblinGuide** [comment]
There's this rumor going around that going over 100% crit chance pushes you back to 0%. If that's actually true (did someone test it?) then using Crit beyond 100% chance is actively detrimental.

Otherwise, yes, it should be used automatically below 100% and used interchangeably with Good Luck Charm above 100%.

**Comment by vanZeben** [comment]
I can test that right now, give me 18 minute (cooldowns and such :()

**Comment by thelulzy** [comment]
Honestly is there any way to know definitively either way?

Wouldn't you need to know what's happening server side to determine what actual impact the crits are having? I was under the impression we weren't even sure whether crit % was crit % per second or crit % per click.

**Comment by vanZeben** [comment]
Level your crit up to over 100% and if it sticks at 101% its false, if its back at 0% its true? Im at 90% atm, so almost there... Mind you they could be capping it at 100% server side, I don't really see how going over 100 would benefit you anyways??

**Comment by GoblinGuide** [comment]
It doesn't benefit you over 100% either way, but using Crit also deploys Good Luck Charm for your lane, if anyone else doesn't have Crit, so it could still be beneficial to spam them?

**Comment by thelulzy** [comment]
Quickly looking at stats such as listed here http://drx.pl/steamgame/ranking_41672.html shows that it displays crit chances > 100%, however there could be a server issue that causes an overflow error back to 0%.

**Comment by ensingm2** [comment]
@brendanvos:  I'm probably going to add in a setting tomorrow that will allow you to toggle on the immediate use of any permanent stat boosters. Currently I have them cast with the same logic as whatever extra ability they cast, and are given priority over use of the base ability. I think this is a better use for them, as you aren't wasting the active ability part of them, but I can see why people want the option. 

@StaplerGuy: I don't see a reason an  overflow would ever happen at a value of 1, so unless they manually coded that overflow condition in, which would be kind of dumb when they can easily just fix it. I really doubt it'll happen. And if we find out that it does happen later on, it'd be trivial to just add a check to make sure you don't overflow before you use it.

**Comment by vanZeben** [comment]
@brendanvos Thanks for that link, I didn't even know it was a thing!

**Comment by ensingm2** [comment]
Should be fixed as of https://github.com/ensingm2/SteamMonsterGameScript/pull/163. Let me know if it isn't.
