### ISSUE TITLE
[Suggestion] Have the scripts display a link on the game page to your room's IRC channel

### ISSUE THREAD

**Issue by thelulzy** [ensingm2/SteamMonsterGameScript#117]
This was originally posted here: https://github.com/wchill/steamSummerMinigame/issues/169
Credit to meekmeekmeek, I just thought I was a great idea which needed visibility on all the major scripts.

I know most of the "official" rooms have dedicated steam groups to chat in. We could also generate links (through a web-irc client website like Mibbit) and if the script added a link on the page, more people would tend to join them.

doing it for an IRC channel would be easy, since you'd just generate the URL based on the room number, even if the channel doesn't exist yet (someone familiar with IRC could go create it then):

```
http://mibbit.com/?channel=%23<channel_name (w/o "#")>&server=<server_address>
```

**Comment by thelulzy** [comment]
Wow, the IRC idea would be a great way to coordinate a room's efforts!

Instead of complicating it with an official channel name or room name the URL could simply have the MSG, or something similar.

**Comment by ensingm2** [comment]
I like this idea, it's pretty simple to implement and we could make a button under the used ability list or somewhere.

> doing it for an IRC channel would be easy, since you'd just generate the URL based on the room number, even if the channel doesn't exist yet (someone familiar with IRC could go create it then)

Any idea if there'd be a way to autocreate on first user join? That'd make things easier. It's been way too long since I've messed around with IRC.

I have some other stuff I need to work on tonight, but I'd be up for working on that tomorrow. It'd be nice to have a standardized channel name structure so all scripts could connect as long as they're in the same room(`"SMG_" + gameID` maybe?)

**Comment by meekmeekmeek** [comment]
I think the first time you join it will actually create the channel for you and make its OP, but it won't be registered so if you leave and the channel empties, the first person to join it will be made OP again: https://wiki.mibbit.com/index.php/Create_your_own_channel

Eg I'm going to open this link now that I just made up:

`http://chat.mibbit.com/?channel=%23WeTestForEnsigm2&server=irc.mibbit.net`

And it worked. I had to choose a username, but it added me to a new empty channel called #WeTestForEnsigm2.

I'll stay in the channel over night, although I probably won't be reading anything till morning.

edit: I just opened the link again from a different browser and ended up in the same channel without issue, without having registered it.

So yeah, this would be really easy to manage, just generate a link like:

http://chat.mibbit.com/?channel=%23SMG_41746&server=irc.mibbit.net

And hope whoever joins first isn't a dick and doesn't register and mute everyone

**Comment by ensingm2** [comment]
Oh.... Can get around the username too!

https://wiki.mibbit.com/index.php/Uri_parameters

Just set `nick` to the user's steam username

Am also interested in `autoConnect`, but looks like it needs an Op to enable it.

**Comment by meekmeekmeek** [comment]
Oh nifty. You were "whidgle" I assume?

I'm in http://chat.mibbit.com/?channel=%23SMG_41746&server=irc.mibbit.net right now, looks like underscores in the channel names don't cause issues.

**Comment by ensingm2** [comment]
Yes, I was. Auto-generated nicks are strange.
