### ISSUE TITLE
[QUESTION] Should we disable enemy HP easing?

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/SteamMonsterGameScript#118]
So the server only updates enemy HP every once in a while, and the client attempts to "smooth" this change over time. This results in some unexpected/unwanted behavior, such as staying on a target after it's actually dead while the client waits for the hp to 'drain down'.

Should we disable the hp easing function and manually do things like check and applydeaths once we get the server message? It wouldn't look as pretty but it'd be a lot more useful and visually accurate.

**Comment by cdmichaelb** [comment]
I vote yes. We're not running this script for pretty.

**Comment by vanZeben** [comment]
Quite honestly I dont see it mattering either way. With the way it is, Its rare to visually see health bars being inbetween full health or 0 (Even on bosses). Mind you right now im in room 41673 and we're clearing levels at 2.68 seconds, so I cant tell how it is for slower rooms...

The issue for me is mostly death/spawn animations (including random coin bursts at their feet), and the item particles

**Comment by vanZeben** [comment]
See #148

**Comment by vanZeben** [comment]
@ensingm2 Do we still need this in here with the FPS Throttle? Same for #114

**Comment by ensingm2** [comment]
Nope!  closed.
