### ISSUE TITLE
Hmmmmmmmmmmmmmmm... Awkward.

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/SteamMonsterGameScript#123]
[Not sure it's an issue (probably isn't in my opinion), just something we should keep in mind, as I hadn't thought about it at all](http://www.reddit.com/r/SteamMonsterGame/comments/39lv9t/customizable_js_autoclicker_targetlanechanger_and/cs84fvm?context=3)

**Comment by thelulzy** [comment]
For some reason the screen is really cramped looking on my 1920x1080 display at 100%, but looks great on my 1600x900.

I've been wondering why that is the whole time.

**Comment by vanZeben** [comment]
Ill rework them into the lower empty portion _shrugs_

**Comment by ensingm2** [comment]
eh, I don't think it's a big deal personally. I am looking into how the game autosizes itself though, may be easier to just make it scale down further than normal.

EDIT: Nevermind, I'm dumb. The game screen doesn't scale. I still don't think this is worth the effort though.

**Comment by vanZeben** [comment]
Yeah the game doesnt autosize, and the stats panel will always be out of the page for them, so it's kinda worth it and not that big of an effort honesty... rotate a psd, edit some css and we good
