### ISSUE TITLE
Auto-integrated leaderboard

### ISSUE THREAD

**Issue by vanZeben** [ensingm2/SteamMonsterGameScript#127]
https://github.com/hansskogvold/steamSummerMinigame/commit/f0f905188585e367f42b756a95d459205190b14f

Would be quite handy to integrate, with the change of viewing which room is you, if it exists in the list

**Comment by ghost** [comment]
Maybe, it could take the place of the recently used abilities. I see no point knowing who used what.

EDIT: Also it just flooding the screen.

**Comment by vanZeben** [comment]
Thats exactly what this does, however it has a toggle below them

**Comment by ghost** [comment]
Sounds useful to me.

**Comment by cdmichaelb** [comment]
Leaderboard isn't working. Every row and column is "undefined".

**Comment by vanZeben** [comment]
Fixed in #131
