### ISSUE TITLE
Liquidate items when server is ending soon.

### ISSUE THREAD

**Issue by cdmichaelb** [ensingm2/SteamMonsterGameScript#133]
Get rid of all items (make it a toggle, in case people want to do something manually)-- Use each item (invuln, lifesteal, revive, wormholes, etc)  on CD starting when you have more items than can possibly be used before the day ends. (Exception: Don't throw money at screen until there are minutes left?)

-Use wormholes a little early incase servers go down early?
--Also, I think you need to kill boss levels while using wormholes? I'm not sure on that one.
---Relax raining gold anti-nuke rules as day is coming to an end.

-Different issue, but kinda of fits with the theme of items: Using an item will update owned items, perhaps use one of the generally useless ones to force an update after each boss wave, or after every 10 boss waves, something like that)

**Comment by ensingm2** [comment]
> Use each item (invuln, lifesteal, revive, wormholes, etc) on CD starting when you have more items than can possibly be used before the day ends. 

Wormholes already implemented by @vanZeben. I'll probably so domething similar with the rest of the items tomorrow.

> Use wormholes a little early incase servers go down early?

Already implemented (well, a 5 min buffer, not sure if that counts)

> Also, I think you need to kill boss levels while using wormholes? I'm not sure on that one.

I don' t think this is the case, I've seen people complaining on forums about using wormholes on bosses wasting gold, so I assumed they got burned by it.

**Comment by cdmichaelb** [comment]
> I don' t think this is the case, I've seen people complaining on forums about using wormholes on bosses wasting gold, so I assumed they got burned by it.

What I mean is you need to defeat a boss level to "check point" your highest level reached (Highest level reached is always a multiple of 10). I'm not sure if skipping a boss level will check point it.  (I can't test it, I don't have any wormholes)

**Comment by ensingm2** [comment]
Oh, yeah. we may want to increase the safe buffer to 10 min or so just to be sure. I dunno.

**Comment by cdmichaelb** [comment]
I was thinking more along the line of (Item Count \* Cooldown) + A little buffer in case they bring the games down early. Rather than a static "10 minutes before scheduled game end"

**Comment by vanZeben** [comment]
That's exactly what @ensingm2 is saying... Currently (with the wormholes at least), that formula is exactly what we use, but the "a little buffer" is 5 minutes

**Comment by ClankTox** [comment]
I know people speculated about wormholes already but has anyone done calculations on collectively spamming "Throw Money at the Screen" in the last half an hour or so of the game?

If you have 60 of them it would take about 10 minutes (without buffer) to drain them, correct?

**Comment by cdmichaelb** [comment]
> That's exactly what @ensingm2 ensingm is saying... Currently (with the wormholes at least), that formula is exactly what we use, but the "a little buffer" is 5 minutes

Ah, in that case never mind :P But I think it would be cool to add it to the other items just cuz why not use my 63+ Invulnerability on CD if the game is coming to an end. Also, kind of on the same thought: Liquidate gold into what can be purchased for damage.

> If you have 60 of them it would take about 10 minutes (without buffer) to drain them, correct?

By my math, yea.

**Comment by vanZeben** [comment]
> spamming "Throw Money at the Screen" in the last half an hour or so of the game?

@ClankTox Im not sure that this would really do much in all honesty, with all the scripts out there using up wormholes in the last ~hour, I would presume that those would just be wasted on levels that just get skipped... Mind you it doesnt hurt at all to just use all the consumables as late as possible, its not like they will stay after it resets anywho

**Comment by ClankTox** [comment]
>Mind you it doesnt hurt at all to just use all the consumables as late as possible
I guess just draining all abilities would be best then as its better than them not being used.

**Comment by ensingm2** [comment]
@vanZeben Actually, it probably would help a pretty good amount if you spam it during the 'buffer period'

Since the cooldown is only 10s, it'd be an easy, fast way to clear the last couple levels and trigger the boss completion after wormholes are all depleted. Not like you need gold in the last 5-10min of the round anyway.

**Comment by vanZeben** [comment]
@ensingm2 I had wrote that before the other scripts had implemented suitable buffers for wormholes and just spammed them if under 30 minutes which would override this, but yeah with a buffer period it helps a bit... Good to see the dump is in there
