### ISSUE TITLE
Add banner telling users not to close tabs, etc.

### ISSUE THREAD

**Issue by vadsamoht** [ensingm2/SteamMonsterGameScript#134]
Even with all of the people saying as much, a lot of people still don't seem to be getting the message that the autoclicker has problems if tabs are closed, minimized or not on top within its window. So why not add a clearly visible  message above the game content that tells the user this?

**Comment by ensingm2** [comment]
I think we actually handle the workaround so it shouldn't matter if you minimize?
See [this issue](https://github.com/ensingm2/SteamMonsterGameScript/issues/120)

I haven't actually tested it, so I'm taking the reddit post linked there and assuming it's correct. Can you confirm that our script still has this issue? If not I'll probably close this.

**Comment by vadsamoht** [comment]
Yes, it seems to work while minimized (at least according to debug output). I must have missed reading that feature in the update logs. Thanks.
