### ISSUE TITLE
Add in some sort of notification of the current level

### ISSUE THREAD

**Issue by vadsamoht** [ensingm2/SteamMonsterGameScript#135]
In the latest version of the script the level number at the top of the playing window has disappeared - I assume this is for performance reasons. Would it be possible to add in some sort of visible counter on the page (say, under statistics), that noted the current level? I guess you could just check one of the leaderboard sites every so often, but it'd be nice to just be able to see the number in the game window somewhere.

**Comment by vanZeben** [comment]
This was fixed in #130
