### ISSUE TITLE
IRC should not use account-name

### ISSUE THREAD

**Issue by SM411** [ensingm2/SteamMonsterGameScript#143]
Using account-name (login name) on IRC is bad for account security. Please use Steam Profile name.

**Comment by Mitarex-git** [comment]
I agree. It's insecure and not logical, because it isn't the same as Steam Community name so people are named differently in-game and in IRC.

**Comment by kevin-abiera** [comment]
We can actually use profile name using:

```
$J('.supernav.username').html().trim()
```

The only problem is that it is not unique (multiple accounts can have the same profile name) unlike the account name. I can create a PR but I cannot test it yet, Steam servers seem down.

**Comment by vanZeben** [comment]
I've already pulled a fix in, using the integrated system... it was just annoying as hell to implement and a bunch of unnecessary code if I did it the quick way
