### ISSUE TITLE
Uncaught ReferenceError: GM_info is not defined

### ISSUE THREAD

**Issue by nuadi** [ensingm2/SteamMonsterGameScript#144]
**Execute method:** Java console
**Version:** 1.99

**Stack trace from console:**

```
Uncaught ReferenceError: GM_info is not defined
  getUploadedFilePath @ VM10532:2086
  addExtraUI @ VM10532:1400
  initGUI @ VM10532:1258
 (anonymous function) @ VM10532:127
```

**Comment by Unknown-Zombie** [comment]
Came to report same thing. My game isn't loading altered UI elements; don't know if it's related to this.

Console output (Chrome):

```
Uncaught ReferenceError: GM_info is not defined
getUploadedFilePath @ (program):2084
addExtraUI @ (program):1398
initGUI @ (program):1256
(anonymous function) @ (program):125
```

**Comment by nuadi** [comment]
Script appears to be working in every other measurable way. Only portion non-functioning is new Statistics and Settings drawers that were at the bottom of the UI.
