### ISSUE TITLE
Slow rendering won't stop

### ISSUE THREAD

**Issue by matan7890** [ensingm2/SteamMonsterGameScript#154]
When I try to disable "slow rendering" it won't close the message about the slow rendering and won't return the fps. I'm using the latest version (2.03) in chrome.

**Comment by vanZeben** [comment]
Checking into it now

**Comment by vanZeben** [comment]
Couldnt replicate it after this, let me know if you can on the latest version

**Comment by matan7890** [comment]
Still doesn't work for me :(

**Comment by matan7890** [comment]
Maybe
```updateToggle("fps", (slowRendering == null));```
Should become:
```updateToggle("fps", (slowRendering != null));```
?

**Comment by ensingm2** [comment]
Seems to be working fine for me as well. Can you let us know what version & browser you're using, as well as if you're using Userscript or copy-pasting the code?

**Comment by matan7890** [comment]
I am using the latest version (2.05 I think, I am not near the computer
right now) with chrome and userscript using tampermonkey. While I tried to
debug it I've found that SlowRendering (or whatever it is called now)
becomes undefined most of the time after I enable the slow FPS, what means
the toggleFPS function doesn't know that I've enabled it. Only if I double
click fast enough on the enabled button it tries to disable the slowfps,
but than things going wrong because the start function has been called more
than once. I hope you understand, it is a little hard to explain it through
the phone...
I also won't be on the computer for a couple of days so I hope you will
find out how to make it work... Thanks!

**Comment by vanZeben** [comment]
Ive noticed it a few times as well... For some inane reason it seems to be setting the setIntevals cached id to undefined randomly without anything being called to set it so :S?

**Comment by ensingm2** [comment]
Alright, I'll try to look into it.

**Comment by vanZeben** [comment]
See, I was noticing it hours ago before I went to sleep, and with my latest push I was intending to check into it again, but now Im not seeing it at all anymore...

**Comment by ensingm2** [comment]
Alright, I haven't seen the issue either. Closing this for now. Reopen if anyone notices it occurring again.
