### ISSUE TITLE
IRC opens in tab in same window as game

### ISSUE THREAD

**Issue by thelulzy** [ensingm2/SteamMonsterGameScript#162]
Causes script to stop running still I believe, correct?

**Comment by ensingm2** [comment]
Assuming commit https://github.com/ensingm2/SteamMonsterGameScript/commit/a173bea8adabd01f8ccbb66a7414a8f3d722408f fixed issue https://github.com/ensingm2/SteamMonsterGameScript/issues/120, it should work fine.

Can you confirm it's not?

**Comment by thelulzy** [comment]
Hmm, i'll leave it on the IRC tab, check back in a half hour and see when my abilities were last deployed

**Comment by thelulzy** [comment]
I have 2 steam accounts on 2 computers in the same room, I can confirm that the script is running while open to a different tab on the same window as the game. 

I watched the deploy feed on my other computer and noticed a deployment by the other account while under these conditions.

I tested the same thing while minimized, it is also working.

I will close this issue.
