### ISSUE TITLE
End Round consumable spam not working

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/SteamMonsterGameScript#180]
[Relevant code](https://github.com/ensingm2/SteamMonsterGameScript/blob/master/automator.user.js#L371-381)

**Comment by zinefer** [comment]
I managed to do some quick debugging before the round finished and I found that it never made it to this line: https://github.com/ensingm2/SteamMonsterGameScript/blob/master/automator.user.js#L376

**Comment by ensingm2** [comment]
yeah I found it too, it's cause the if statement in the line beforehand should be `ABILITIES.RESURRECTION`, not `ABILITIES.RESURRECT`. I'm testing a fix now but running into some other issues.

**Comment by ensingm2** [comment]
Should be fixed as of https://github.com/ensingm2/SteamMonsterGameScript/commit/3dd086201e89ca4b466e93b40caceb9960212084

JK https://github.com/ensingm2/SteamMonsterGameScript/commit/d9f9de8ebb142682c21bd91e410416a196ca21d7
