### ISSUE TITLE
Survival time does not stay upon refresh

### ISSUE THREAD

**Issue by sinnoaria** [ensingm2/SteamMonsterGameScript#181]
This may have already been fixed, but when you do a manual refresh (unsure about auto refresh), if you have survival time set to anything but 30, it returns to 30 after the refresh.

Not sure about other variables in the settings.

**Comment by ensingm2** [comment]
it was fixed about an hour ago with https://github.com/ensingm2/SteamMonsterGameScript/commit/173ae1a98c95cfcc5b096beec53148f22a9c5b0b

I tested, but let me know if that's not the case. Closing this for now.
