### ISSUE TITLE
Counteract built in anti-autoclicker

### ISSUE THREAD

**Issue by russelg** [ensingm2/SteamMonsterGameScript#19]
http://www.reddit.com/r/SteamMonsterGame/comments/39ny04/monster_game_seems_to_have_built_in/

Setting `g_msTickRate = 1100` regularly may be a way to get around this.

**Comment by ensingm2** [comment]
Fix was completed and live ~3 hours ago. I also posted that I did so in that thread :x 
Please try to check the commit logs or code.

Relevant commit: https://github.com/ensingm2/SteamMonsterGameScript/commit/66cd457ea5aa51e239fe0fa4830b12b4d43fce20

**Comment by russelg** [comment]
Whoops LMAO

I thought this wasn't done as 20 was still being used, but with the method it's being used is fine. Apologies.
