### ISSUE TITLE
Script overwrites clicks rather then incrmenting them

### ISSUE THREAD

**Issue by brickmaster32000** [ensingm2/SteamMonsterGameScript#22]
From the looks of it if you manually click they will be overwritten by the script when it updates the number of clicks.

**Comment by DannyDaemonic** [comment]
I assume this is intentional. The game itself limits you to 18 clicks, so there's no advantage to doing more. I suppose it could use the max of the user clicks vs auto generated clicks, but again, it won't benefit you.

**Comment by DannyDaemonic** [comment]
See [this post](https://www.reddit.com/r/SteamMonsterGame/comments/39ny04/monster_game_seems_to_have_built_in/) on Reddit for more information.

**Comment by ensingm2** [comment]
Yeah, this was intentional, I figure I might as well made it an addition though for people who want to do both, so I did a little bit ago.
