### ISSUE TITLE
Sometimes doesn't target bosses

### ISSUE THREAD

**Issue by Evanito** [ensingm2/SteamMonsterGameScript#25]
Ive noticed the script will occasionally (more often than not) refuse to target a boss, and will instead try and focus on a miniboss. Even if I manually change lane it will instantly pull back to the miniboss. Occasionally (when the boss spawns in the lane the script was already in) it will work as expected.

**Comment by Inevitable** [comment]
Confirming this behavior with 1064b9d0ec

**Comment by thelulzy** [comment]
Issue still appears to be at least somewhat present in 7bafe47451

It's becoming difficult to tell what behavior is actually happening and what is simply client update delay in my group as we're at lvl 1565 and killing bosses nearly instantly.

**Comment by DannyDaemonic** [comment]
I'm getting the same thing. It does seem to eventually pick the right lane, but I can't think of a reason for the delay. The delay is too long just to be lag.

**Comment by seyguai** [comment]
The 'IsGold' priority applied without checking the 'TypePriority' probably causes this.

At least, adding `&& (mobB.m_data.type == 3 || mobB.m_data.type == 1)` to the gold check block within `compareMobPriority` function seems to fix the problem:
l754: `if(aIsGold > bIsGold && (mobB.m_data.type == 3 || mobB.m_data.type == 1)) {`
(switching to raining gold target only if current target is a miniboss or a normal monster)

This is not a complete solution, but might work as temporary fix for those who wants to keep focus on the boss / spawner in lane.

**Comment by ensingm2** [comment]
@seyguai: I'm not sure I see the problem here. Unless a boss is just about to die, you stand to gain more gold from even a creep with raining gold on. Also, your proposed change makes you only swap AWAY from bosses/minibosses for raining gold. Shouldn't it be the other way around? EDIT: oops, you're right, got my mobType IDs mixed up.

@brendanvos, @DannyDaemonic: You're correct about the client update delay. You actually only get game state updates every few seconds and your client just tries to guess what the total damage done to a target is in that window before an update.

**Comment by seyguai** [comment]
On the paper, it works like you say.
In the game, there will be someone to nuke the boss before the script can switch lanes. Not everytime, but it does happen.
I have not seen any data telling me how much each monster gives, but i'm rather happy seeing my gold counter going up 1T/s when auto attacking a boss.

About my code, it only allows the switch when the mobB (i.e. the current monster targeted) is a miniboss or a normal monster, which means it will **not** allow to switch target if the current one is a treasure/spawner/boss.
The compare method is a bit hard to get :/

**Comment by ensingm2** [comment]
@seyguai: You're right. Added with https://github.com/ensingm2/SteamMonsterGameScript/commit/df91507c8720c1821eb0d96c8abb790e64a5fb40
