### ISSUE TITLE
Metal Detector never being used

### ISSUE THREAD

**Issue by thelulzy** [ensingm2/SteamMonsterGameScript#28]
The bosses are dying to quickly in the planned rooms.

The script never has a chance to deploy Metal Detector because the boss's health typically drops instantly, bypassing the 30% health deploy condition. I would suggest changing Metal Detector to deploy on boss, regardless of remaining health.

**Comment by DannyDaemonic** [comment]
It is configurable if you don't use the minified version. Look for the variable **useMetalDetectorOnBossBelowPercent** and set it to 100 to deploy instantly.

The ideal solution would be to calculate the DPS focused on the boss and predict based on that. Knowing how fast health is dropping would be useful in other areas of the code as well, but that info isn't currently calculated.

**Comment by ensingm2** [comment]
You can still use the minified version and just tack on an assignment at the end.  As far as optimizing metal detector, I'll probably work on that after automating the other items

**Comment by ensingm2** [comment]
Updated to estimate time until boss death based on lane DPS, and trigger Metal Detector if the estimated time of death is within 10s (duration is 20, so should have enough leeway).

This may run into issues with DPS spikes due to people nuking bosses, but it should at least be better. We'll see.

**Comment by DannyDaemonic** [comment]
Can we watch for nuke events and subtract that from the lane DPS?
