### ISSUE TITLE
Script failure since 1.21 (gold count update)

### ISSUE THREAD

**Issue by seyguai** [ensingm2/SteamMonsterGameScript#29]
l67: `if( enemy != undefined && nClickGoldPct > 0 && enemy.m_data.hp > 0)`

`m_data` is never checked, which makes the script fails when `undefined`.

![ss 2015-06-13 at 08 41 20](https://cloud.githubusercontent.com/assets/12875409/8145547/a359a94a-120c-11e5-88a8-82183332c239.png)

**Comment by ensingm2** [comment]
This has been fixed.
