### ISSUE TITLE
Crits Ability doesn't auto deploy

### ISSUE THREAD

**Issue by thelulzy** [ensingm2/SteamMonsterGameScript#30]
This isn't so much an issue. It's more of a lack of feature, but issues have the highest visibility to those developing.

Crits causes a permanent increase to your crit chance, and thus should be deployed immediately.

**Comment by ensingm2** [comment]
It should now auto-deploy instead of Morale Booster if you have one available, have autoItemUser enabled, and it meets the Morale Booster autoUse conditions.
