### ISSUE TITLE
Options Toggle Buttons Issues

### ISSUE THREAD

**Issue by medlir** [ensingm2/SteamMonsterGameScript#31]
Need to add the toggle functions to the unsafeWindow exports so they can be used from a userscript.  Also, the toggle for TargetSwapper is checking autoUpgradeManager rather than autoTargetSwapper.

**Comment by cdmichaelb** [comment]
autoUpgrade should be default off as it can be destructive before people disable it. (e.g. I don't like how it decides to upgrade elements)

**Comment by ensingm2** [comment]
@medlir: this should be fixed now, let me know if it isn't.

@Miv333: That's not why TargetSwapper is being wonky. It's just being buggy, I'm not 100% sure why at the moment but it's probably next on my list of things to do.
