### ISSUE TITLE
ReferenceError: g_TuningData is not defined

### ISSUE THREAD

**Issue by MightyBirdy** [ensingm2/SteamMonsterGameScript#33]
This is what Firefox gives me. The game doesn't even load in Chrome.

**Comment by ensingm2** [comment]
Not sure what your problem is. Works fine for me and others in both chrome and firefox, using userscript and copying manually.  g_TuningData is one of the first  assigned variables when in game.

You probably either have addons interfering or are using the script incorrectly.
