### ISSUE TITLE
Display next upgrade buy target somewhere

### ISSUE THREAD

**Issue by CrashCat** [ensingm2/SteamMonsterGameScript#34]
It's hard to tell sometimes if the upgrade buyer is working because it is waiting for a very expensive upgrade.  Could we get a display of the next upgrade to be bought somewhere on the screen?  Might even be nice to display the 'second place' choice and the DPS/coin for each so we can decide if we feel it's not worth waiting for "the big one".

**Comment by Evanito** [comment]
This would be helpful. All I have noticed the bot upgrading is my elemental damage (all in fire for some reason)

**Comment by ensingm2** [comment]
@CrashCat: the guy that wrote the autoBuyer script is updating it, so hopefully after that happens we can add something along those lines.

@Evanito: See http://www.reddit.com/r/SteamMonsterGame/comments/39oyrw/upgrading_of_only_one_element_is_more_efficient/

**Comment by ensingm2** [comment]
Fixed in https://github.com/ensingm2/SteamMonsterGameScript/pull/64
