### ISSUE TITLE
"startAutoUpgradeManager()" is not a recognised command ALSO buttons don't all work

### ISSUE THREAD

**Issue by Evanito** [ensingm2/SteamMonsterGameScript#37]
As title says. I didnt have time to fiddle with the buttons but I noticed that several of them (not all) did nothing when pressed (or at least did not show it, as their names (disable/enable this blah blah) stayed stuck at "disable this"

When I was trying to disable everything through console I also discovered that the command to restart autoupgrade is missing (it was the only feature I wanted at the time)

Edit: May I suggest a 30second(or so) timer that checks whether each button should say disable or enable? In addition to it toggling on click, of course.

**Comment by ensingm2** [comment]
1. There was an issue for a while with UserScript scope that stopped this. Should work now.
2. Yeah looks like the person that added the function to resolve the scope issues happened to miss that function. Fixed.
3. Probably not, this would be extra performance overhead for a feature that almost nobody would use. You'd have to be someone that toggles things both through the console and the UI, and at that point you should know what's going on.
