### ISSUE TITLE
"Spawn slaves" button is clicking itself every several minutes

### ISSUE THREAD

**Issue by ghost** [ensingm2/SteamMonsterGameScript#40]
It's very annoying because it stops the game execution.

**Comment by brammator** [comment]
same here.  FF 35.0.1, greasemonkey version of script.

**Comment by Inevitable** [comment]
Confirming behavior on Chrome 64 beta, Tampermonkey version

**Comment by ghost** [comment]
Even removing this button from GUI via "Inspect element" didn't helped.

**Comment by JimRaynor56** [comment]
This should be resolved with the 1.47 update.  I'm testing it now.

EDIT: Seeing the same issue as chrisgavinme

**Comment by chrisgavin** [comment]
Newest update fixed the issue for me but now I can't spawn slaves at all.

ReferenceError: slaveWindowCount is not defined

**Comment by brammator** [comment]
Workaround: wait until dialog pops, then wait enough time to have second pop.  Browser will ask if you want block this site from spawning dialogs.

**Comment by Inevitable** [comment]
Confirming this behavior still in 4bcd0e4df7cfe3739e3dd58a6dc39c8bd0302865

**Comment by longzheng** [comment]
The slave code is designed to auto refresh every 5 minutes by killing all slaves and recreating them. https://github.com/ensingm2/SteamMonsterGameScript/blob/master/slaveWindows.js#L49-L61

~~The annoying part here is that the code prompts the user every time and does not remember last choice. https://github.com/ensingm2/SteamMonsterGameScript/blob/master/slaveWindows.js#L26~~ The code that remembers the previous slave window count doesn't seem to be working https://github.com/ensingm2/SteamMonsterGameScript/blob/master/slaveWindows.js#L53

**Comment by JimRaynor56** [comment]
Seems to be completely solved with 8f3fd26c44c5bd8acd4d72808dfef6b4ea35e9ee.

**Comment by ensingm2** [comment]
Cool. On to https://github.com/ensingm2/SteamMonsterGameScript/issues/41. Reopen if needed.
