### ISSUE TITLE
Slaves are meant to automatically respawn, but don't always do so.

### ISSUE THREAD

**Issue by JimRaynor56** [ensingm2/SteamMonsterGameScript#43]
I'll see in the log "spawning # slave windows."  But they won't actually spawn.

**Comment by JimRaynor56** [comment]
This is an intermittent issue I have.  Not sure what's causing it.  Debug logs don't seem to point to anything specific.  I'll keep collecting data and see if I can see a pattern.

**Comment by ensingm2** [comment]
It's almost definitely your browser blocking popups. Disable your popup blocker or whitelist the page.

**Comment by JimRaynor56** [comment]
This is a fresh install of the Firefox Developer Edition x64, and I whitelisted the page with the built-in popup blocker already.

Like I said, it's intermittent.  Sometimes they spawn properly, other times they don't.

**Comment by JimRaynor56** [comment]
It might be related to you pushing updates to the script.  When my script auto-updated with fc285f71375d1f034ca614ec19e716c0f78eb35c the next set of spawns didn't go off properly.

There's not really a way to fix that, I think.  So I'm going to go ahead and close this.

**Comment by JimRaynor56** [comment]
Definitely resolved now by 4be164ada55f97a313eeef1e1688bfbb93633256.
