### ISSUE TITLE
Auto-buyer received major update; need to merge

### ISSUE THREAD

**Issue by meishuu** [ensingm2/SteamMonsterGameScript#44]
I've just done a [major update](https://gist.github.com/meishuu/f83ee1de2992d5fc656c/revisions) to the standalone version but it requires another global variable to maintain persistence and is probably all-around messy to toggle all functionality on/off at will.

I'd be willing to merge this myself but I'm super sleepy. If someone else can do it, please feel free and say so, otherwise I'll work on it once I wake up.

Summary of changes:
- Added setting to enable buying abilities; **off by default**
- Fixed `necessaryUpgrade()` computing costs incorrectly
- `bestDamageUpgrade()` now accounts for effects of crits and elementals in all cases (fixes #35)
- `bestDamageUpgrade()` also checks locked click damage upgrades to see if unlocking them and getting the first upgrade is worth it
- `timeToDie()` now only ever updates on new levels or when an upgrade was purchased
- If an upgrade purchase fails to go through, we try to force a data refresh before recalculating next item (also fixes script entirely breaking if an upgrade fails to go through)
- Successful upgrade purchase, _now including manual ones_, will force an early re-evaluation of next item, so the timer now only serves to wait until we have enough gold to purchase the queued item (I think)

Someone can probably just pick out the changes relevant to fixing `bestDamageUpgrade()` for now. Also, I've just now noticed a change to a single element strategy so that could use some fiddling.

**Comment by ensingm2** [comment]
"I'd be willing to merge this myself but I'm super sleepy. If someone else can do it, please feel free and say so, otherwise I'll work on it once I wake up."

Same deal. 8:30am here and I forgot to sleep. Going to bed,  I'll toy with it if nobody else has when I wake up.

**Comment by waterfoul** [comment]
I'll start trying this now and send a PR

**Comment by JimRaynor56** [comment]
It's going to need another update to account for the new upgrades.

**Comment by waterfoul** [comment]
Reading through the code I believe it will handle the new upgrades automatically, need to confirm though

**Comment by ensingm2** [comment]
Unless I'm mistaken (I only quickly glanced at the update, focusing on my massive inbox right now),  the new upgrades need to be added to the gHealthUpgrades & gDamageUpgrades arrays, after which point they will work?

If you could add that, or confirm new upgrades are indeed working, it'd be awesome. Otherwise I'll add them once I  get around to figuring out the new ability IDs

**Comment by ensingm2** [comment]
Should (Hopefully) work now. Reopen if that's not the case.
