### ISSUE TITLE
Slave windows will refresh during Boss

### ISSUE THREAD

**Issue by Inevitable** [ensingm2/SteamMonsterGameScript#46]
Per title, there is currently no check for Boss encounters in the slave window refresh logic; it's simply time based.  This causes situations where the slaves will refresh mid-boss encounter which is not desirable.

Additionally, it would be ideal to add a yrs/no pass to the behavior for those that want to manually manage huge slave window counts which would be unfeasible for automated mass reloading.

**Comment by ensingm2** [comment]
Should be fixed as of https://github.com/ensingm2/SteamMonsterGameScript/commit/1a9df05cbb398d6736c628c9d7b41648c86d57ff .

Didn't have time to test extensively, so let me know if things don't seem to be working.

EDIT: allowing people to not refresh is on my list of things to do, just need sleep first.
