### ISSUE TITLE
Suggestion: Refresh slave windows sequentially rather than simultaneously.

### ISSUE THREAD

**Issue by JimRaynor56** [ensingm2/SteamMonsterGameScript#47]
This would help with #46 as well as prevent a massive spike in resource usage when refreshing large numbers of slaves at the same time.

Especially so if you wait to start the next one until after the graphics have been removed from the slave window.

**Comment by thelulzy** [comment]
Are slaves still having an effect? I'm not seeing any impact when using slaves.

**Comment by ensingm2** [comment]
Should be fixed as of https://github.com/ensingm2/SteamMonsterGameScript/commit/7285f29f254df35a33aabe43887bb3ceccc0b041

However, Github caches the script so it may take a little while to take effect.
