### ISSUE TITLE
Auto scripts being restarted constantly

### ISSUE THREAD

**Issue by kurtd5105** [ensingm2/SteamMonsterGameScript#48]
I pasted in the most recent minified.js into the console, making sure I had the whole script selected and I tried it twice, once after a refresh. 
I am using the latest Opera browser with my user agent set to the latest Chrome (if that matters).
The console logs the following, over and over:
UpgradeManager is already running!
VM268:2 Autoclicker is already running!
VM268:2 autoRespawner is already running!
VM268:2 autoTargetSwapper is already running!
VM268:2 autoAbilityUser is already running!
VM268:2 autoItemUser is already running!
VM268:2 UpgradeManager is already running!
VM268:2 Autoclicker is already running!
VM268:2 autoRespawner is already running!
VM268:2 autoTargetSwapper is already running!
VM268:2 autoAbilityUser is already running!
VM268:2 autoItemUser is already running!
VM268:2 UpgradeManager is already running!

and it keeps spamming the buttons.

EDIT: I tested the non-minified script with ViolentMonkey, and it works perfectly fine.

**Comment by Brettflan** [comment]
Same thing for me with the minified copy as of most recent commit 273fcd7 running in Chrome. I ended up just getting the minified copy from 8f6378a which works fine.

**Comment by Brettflan** [comment]
Fixed for me as of caea6fa.
