### ISSUE TITLE
Need to add autocasting of new BP abilities

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/SteamMonsterGameScript#54]
'Wormhole', 'Like New',  etc.

**Comment by ensingm2** [comment]
Implemented Like New.

Wormhole and Feeling Lucky don't seem to have good, well defined "best cases" for auto uses. 

Possibly Wormhole on Spawner levels (check for treasure mobs first)?
Feeling Lucky when a certain percentage of the game's players are alive and in lane?

**Comment by Evanito** [comment]
Ideas I have had for wormhole:
1) Require it is activated manually. (After all, it is equivalent to 1000 levels of BP)
2) Only do it on non-boss levels after about level 1000 (to get a nest egg going), if the level has just started.

**Comment by ensingm2** [comment]
Yeah, idk. I'll probably just leave it on manual for now. Closing this.
