### ISSUE TITLE
slaveWindows.js being cached by UserScript and not updating

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/SteamMonsterGameScript#59]
Current workaround is to delete/reinstall the userscript, but that's a huge pain in the ass. If anyone knows a better way to force it to update, please let me know.

**Comment by AlinaNova21** [comment]
Maybe try adding a querystring to the end of the url? Its a trick i've used in pure html to force cacheless  load. (It can be a static querystring, just it being there is usually enough)

**Comment by ensingm2** [comment]
Are you sure a static query works? In my experience with that workaround you generally need to send it rand or a timestamp or something.

since it's a UserScript include, it MUST be static.

**Comment by waterfoul** [comment]
The querystring will work as ling as you change it every time the slaveWindows.js changes

**Comment by ensingm2** [comment]
Good point. I'll add it in next time that script changes (if it does) since it hasn't been updated in a while and any current caches are most likely up to date. Closing this issue.
