### ISSUE TITLE
Visual effects

### ISSUE THREAD

**Issue by Rawrlex** [ensingm2/SteamMonsterGameScript#60]
Could you disable them all? Running your script on my vServer and its lagging hard through remote desktop. Like conis popping up and the other visual effects. And yes, I did not enable Particle Spam.

**Comment by ensingm2** [comment]
'$J('body > *').hide(); g_Minigame.Renderer.render = function(){};'

**Comment by Rawrlex** [comment]
Isn't fixing the problem for me if I type it in the console.

**Comment by ensingm2** [comment]
Did you run it without the quotes?

**Comment by Rawrlex** [comment]
I did not, should I?

**Comment by ensingm2** [comment]
Yes.

**Comment by Rawrlex** [comment]
Tyvm, you should implement this as an option if your time allows it. Maybe tomorrow or something. :) Ty again!

**Comment by ensingm2** [comment]
I chose not to add it because there's no way to toggle the visuals back on (until you refresh the page) if you do this.

**Comment by Rawrlex** [comment]
Then maybe write a notice behind it. I really think many people would like to see this performance update.
