### ISSUE TITLE
Low health doesn't deploy Pumped Up

### ISSUE THREAD

**Issue by aph3rson** [ensingm2/SteamMonsterGameScript#70]
Pumped Up also deploys a complimentary Medic ability - therefore, if health is low, shouldn't it be used if no Medics are present?

**Comment by ensingm2** [comment]
Are you sure this is the case?

see https://github.com/ensingm2/SteamMonsterGameScript/blob/master/automator.user.js#L784-816

**Comment by aph3rson** [comment]
That bit of code would make me think otherwise, but I watched as it ignored my Pumped Up about three times, and died instead. The lanes were not medic lanes - they may have been some kind of gold lane, though, can't quite remember.

**Comment by ensingm2** [comment]
Do you have low enough max health that you're dropping from the 'safe' theshold (<30% max hp) to dead in the time it takes between Ability use rechecks(2s)?

I guess it could also be due to the delay of using an ability, and dying before the server recognizes you.

Have you noticed if you've been autoUsing the other health abilities (Medic and Steal Health)?

I may bump up the threshoold to 40% max hp or so.

**Comment by aph3rson** [comment]
It does use Medic when need be, though I haven't observed Steal Health being used (don't even know if I've ever gotten one).

Also, I have a health that takes about 5 seconds to go from 30% to 0%. Turning on debug said that there are no available medic lanes/abilities.

**Comment by ensingm2** [comment]
I think it should be fixed in https://github.com/ensingm2/SteamMonsterGameScript/commit/6632d114095dc839aeb1165e46f626861c121ec0. Can you confirm?

**Comment by aph3rson** [comment]
At a later time, I don't have the Pumped Up ability.

**Comment by ensingm2** [comment]
I at least stepped through the logic manually. Looks like things should work?

See the first 2 line changes of https://github.com/ensingm2/SteamMonsterGameScript/commit/c1b6e9ff8065577083eb25e33ee603193543ee16 .

Also Increased use threshold to 40% max hp and still allow medic use if another one is active in lane (but only one other, more than that we hopefully shouldn't need to trigger ourselves)
