### ISSUE TITLE
Uncaught ReferenceError: useResurrectBelowLaneAlive is not defined

### ISSUE THREAD

**Issue by Evanito** [ensingm2/SteamMonsterGameScript#71]
As title says, I get this error in console once every few seconds. I have two resurrects.

**Comment by ensingm2** [comment]
Oops, changed a variable name and missed a reference to it (Hard to test these things when I don't actually have the item :X). Can you verify it's working as of https://github.com/ensingm2/SteamMonsterGameScript/commit/08d8b59dbce35b77a2830a51fa780801081cd196 ?

**Comment by Evanito** [comment]
Affirmative, works as expected, even used a resurrect once I refreshed.

**Comment by xImpulse** [comment]
This is actually more broken for me after this update: https://github.com/ensingm2/SteamMonsterGameScript/commit/08d8b59dbce35b77a2830a51fa780801081cd196
The resurrection ability is being auto-used continuously even if no players are dead in any lane. Before this version, I don't think the ability was auto-used at all.

**Comment by ensingm2** [comment]
Fuck me. Yeah you're right, looks like I typo'd and it only used if under the threshold of people were dead, not over. Fixing now (Of course I'm stuck in a 'waiting for players to join' so it'll be a minute or two before I can test).

**Comment by ensingm2** [comment]
I think it should be fixed in 6632d11. Can you confirm?

**Comment by Evanito** [comment]
Im out of resurrects so don't look at me haha

**Comment by ensingm2** [comment]
Tested. SEEMS to be working now.

**Comment by xImpulse** [comment]
Seems to be fixed. Thanks for your awesome script!
