### ISSUE TITLE
Keep geting this return and pretty sure it's not autoclicking

### ISSUE THREAD

**Issue by Gruntydog** [ensingm2/SteamMonsterGameScript#72]
running.js:804:4
Got stale data for time 1434334166, requesting data again next tick...

**Comment by ensingm2** [comment]
That just means that the data you received from the server is out of date, so it requests it again.

What makes you 'pretty sure it's not autoclicking'?

**Comment by Gruntydog** [comment]
I keep getting no gold gains during, Raining Gold.

**Comment by Gruntydog** [comment]
Just reinstalled works now, thanks for the script.
