### ISSUE TITLE
Auto-buy Glow

### ISSUE THREAD

**Issue by meishuu** [ensingm2/SteamMonsterGameScript#74]
I didn't notice you added this so I ended up with my own implementation.

![Example](http://i.imgur.com/hvLCrh7.png)

I've also added a few things to the autobuyer, so I'm just waiting on word for what to do with this before (i.e., replace with mine, keep yours, or combine) before I go ahead and merge:
- future-proofed so we don't need to update for new upgrade tiers
- armor and auto-dps now do proper calculations for checking locked upgrades
- general cleanup

**Comment by vanZeben** [comment]
Personal opinion; I like this implementation more than the quick hack I threw together... It's a lot more in sync with the UI

**Comment by ensingm2** [comment]
I like this implementation better personally, it's more apparent, I'm down to replace with yours.

Just to be sure though, that gold in the SS is "next buy" and different than "I have enough money but haven't bought yet" right?

**Comment by vanZeben** [comment]
How I took these, was those are all the next buy, but in different situations (first ss was can afford, second was cannot, same with elementals)

**Comment by ensingm2** [comment]
ah, ok cool. Sounds good to me.
