### ISSUE TITLE
Elemental Damage Upgrade Selections are Stacking on One Elemental Type Only

### ISSUE THREAD

**Issue by DrGirlfriend** [ensingm2/SteamMonsterGameScript#82]
So far today I have see that only one type of elemental upgrade type is purchased which doesn't make sense to me since the monster elemental weakness is random and not all players are using this script. I would think based on the randomness of the monster weakness towards a particular elemental damage, Elemental Damage upgrade purchases should be even across all 4 types.

**Comment by cdmichaelb** [comment]
I agree, the way the script is designed, it doesn't work well with favoring a single element.

**Comment by ensingm2** [comment]
Working as intended. For a detailed explanation as to why each person should favor one element, see this post:
http://www.reddit.com/r/SteamMonsterGame/comments/39oyrw/upgrading_of_only_one_element_is_more_efficient/
