### ISSUE TITLE
Dump Gold feature in autoUpgrader

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/SteamMonsterGameScript#91]
It'd be nice to have a "dump all gold" function to buy everything possible. This would allow us to prep and use our 'throw money at screen' items. As is, they're pretty useless.

**Comment by DannyDaemonic** [comment]
Big upgrades take a while to get after a while, personally I'd just rather just have some logic that saves my throw money at screen items for the last 10 minutes of the round.
