### ISSUE TITLE
Music starts on slave windows at boss fights

### ISSUE THREAD

**Issue by NoisyFlake** [ensingm2/SteamMonsterGameScript#92]
When you open slave windows, the music in the main window turns off. After turning it on again, the music starts playing in all slaves as soon as a boss appears - and there's no way to turn it off (except for killing all slaves) because you can't access the slave controls.

**Comment by JimRaynor56** [comment]
This is a duplicate of #41 and it has been resolved.  You can either leave it off, or deal with the duplicate sounds.  There is no good way to fix it.
